from datetime import date

import pytest

from member.generate import TARGETS, generate_sleep_profile, generate_usage_nights

STUDY_DATE = date(2026, 1, 10)


def test_generation_is_deterministic():
    """A golden case that cannot be regenerated byte-for-byte is not a golden case."""
    first = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)
    second = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)

    assert first == second


def test_different_members_get_different_profiles():
    """Seeded on the member as well as the seed, so one population is not 500 copies."""
    a = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)
    b = generate_sleep_profile("M2", seed=7, study_date=STUDY_DATE)

    assert a != b


def test_ahi_is_consistent_with_the_raw_counts():
    """AHI is events per hour of recorded sleep. If the derived index disagreed with the
    counts, one criterion would pass and its sibling fail on the same study."""
    profile = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)

    assert profile.ahi == pytest.approx(profile.apnea_events / profile.recorded_hours, abs=0.05)


@pytest.mark.parametrize(
    "target,low,high",
    [
        ("qualifying", 15.0, 100.0),
        ("mild_range", 5.0, 14.0),
        ("below_threshold", 0.0, 4.99),
    ],
)
def test_targets_land_in_their_band(target, low, high):
    for member in (f"M{i}" for i in range(30)):
        profile = generate_sleep_profile(member, seed=3, study_date=STUDY_DATE, target=target)
        assert low <= profile.ahi <= high


def test_near_miss_high_is_below_fifteen_but_only_just():
    """ADR-0009: a refusal set of obviously-out-of-scope cases measures the easy half of
    the problem. This is the case that must not be approved and nearly is."""
    for member in (f"M{i}" for i in range(30)):
        profile = generate_sleep_profile(
            member, seed=3, study_date=STUDY_DATE, target="near_miss_high"
        )
        assert 14.0 <= profile.ahi < 15.0


def test_borderline_high_qualifies_exactly_at_the_threshold():
    profile = generate_sleep_profile("M1", seed=3, study_date=STUDY_DATE, target="borderline_high")

    assert profile.ahi == 15.0


def test_an_unknown_target_raises():
    """Silently falling back to a default would produce a golden case that does not test
    what its name says it tests."""
    with pytest.raises(ValueError, match="target"):
        generate_sleep_profile("M1", seed=3, study_date=STUDY_DATE, target="nonsense")


def test_adherent_usage_clears_seventy_percent():
    nights = generate_usage_nights("M1", seed=5, start=date(2026, 2, 1), nights=30)
    qualifying = sum(1 for _, hours in nights if hours >= 4.0)

    assert len(nights) == 30
    assert qualifying / 30 > 0.70


def test_near_miss_adherence_falls_just_short():
    nights = generate_usage_nights(
        "M1", seed=5, start=date(2026, 2, 1), nights=30, target="near_miss_adherence"
    )
    qualifying = sum(1 for _, hours in nights if hours >= 4.0)

    assert 0.60 <= qualifying / 30 < 0.70


def test_usage_nights_are_contiguous_and_unique():
    nights = generate_usage_nights("M1", seed=5, start=date(2026, 2, 1), nights=30)
    days = [night for night, _ in nights]

    assert len(set(days)) == 30
    assert days == sorted(days)


def test_every_target_is_reachable():
    """A target named in TARGETS but unhandled would fail only when a golden case used it."""
    for target in TARGETS:
        assert target
