from datetime import date

import pytest

import member.generate as generate_module
from member.generate import TARGETS, TEST_TYPES, generate_sleep_profile, generate_usage_nights

STUDY_DATE = date(2026, 1, 10)


def test_generation_is_deterministic():
    """A golden case that cannot be regenerated byte-for-byte is not a golden case."""
    first = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)
    second = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)

    assert first == second


def test_different_members_get_different_profiles():
    """Seeded on the member as well as the seed, so one population is not 500 copies."""
    a = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)
    b = generate_sleep_profile("M2", seed=7, study_date=STUDY_DATE)

    assert a != b


def test_ahi_is_consistent_with_the_raw_counts():
    """AHI is events per hour of recorded sleep. If the derived index disagreed with the
    counts, one criterion would pass and its sibling fail on the same study."""
    profile = generate_sleep_profile("M1", seed=7, study_date=STUDY_DATE)

    # Exact equality, not a tolerance: ahi is this division and nothing else, so any
    # slack here would hide a future change that started rounding the one derived value.
    assert profile.ahi == profile.apnea_events / profile.recorded_hours


@pytest.mark.parametrize(
    "target,low,high",
    [
        ("qualifying", 15.0, 100.0),
        ("mild_range", 5.0, 14.0),
        ("below_threshold", 0.0, 4.99),
    ],
)
def test_targets_land_in_their_band(target, low, high):
    for member in (f"M{i}" for i in range(30)):
        profile = generate_sleep_profile(member, seed=3, study_date=STUDY_DATE, target=target)
        assert low <= profile.ahi <= high


def test_near_miss_high_is_below_fifteen_but_only_just():
    """ADR-0009: a refusal set of obviously-out-of-scope cases measures the easy half of
    the problem. This is the case that must not be approved and nearly is."""
    for member in (f"M{i}" for i in range(30)):
        profile = generate_sleep_profile(
            member, seed=3, study_date=STUDY_DATE, target="near_miss_high"
        )
        # Strictly above 14.0, the mild band's ceiling, not merely at or above it: at
        # exactly 14.0 this profile is also inside the 5-14 band, where a documented
        # symptom or comorbidity approves it. `>=` encoded that overlap instead of
        # catching it. The composed consequence is in tests/test_fixture_population.py.
        assert 14.0 < profile.ahi < 15.0


def test_just_qualifying_clears_fifteen_but_only_just():
    """The approval that sits closest to the line. The refusal side had three
    near-misses and the approval side none, so (15, 20) was unbuildable -- and a
    boundary is only tested from one direction if only one direction is constructible."""
    for member in (f"M{i}" for i in range(30)):
        profile = generate_sleep_profile(
            member, seed=3, study_date=STUDY_DATE, target="just_qualifying"
        )
        assert 15.0 < profile.ahi < 20.0


def test_borderline_high_qualifies_exactly_at_the_threshold():
    profile = generate_sleep_profile("M1", seed=3, study_date=STUDY_DATE, target="borderline_high")

    assert profile.ahi == 15.0


def test_near_miss_channels_is_an_accepted_type_that_fails_the_channel_minimum():
    """NCD 240.4.1 accepts a Type IV study only with at least 3 channels. This is the
    near-miss for that criterion -- a real, in-scope test type, one channel short --
    the same way near_miss_high is the near-miss for the AHI criterion."""
    for member in (f"M{i}" for i in range(30)):
        profile = generate_sleep_profile(
            member, seed=3, study_date=STUDY_DATE, target="near_miss_channels"
        )
        assert profile.test_type == "home_type_iv"
        assert profile.channels == 2
        # Qualifies comfortably on AHI, so the case fails on test-type validity
        # alone -- the criterion under test isn't confounded by the AHI criterion.
        assert profile.ahi >= 15.0


def test_invalid_test_type_is_outside_the_accepted_enum():
    """A negative case for the "is this an accepted study type at all" check, distinct
    from near_miss_channels' "accepted type, wrong channel count"."""
    for member in (f"M{i}" for i in range(30)):
        profile = generate_sleep_profile(
            member, seed=3, study_date=STUDY_DATE, target="invalid_test_type"
        )
        assert profile.test_type not in TEST_TYPES
        assert profile.ahi >= 15.0


def test_severity_is_independent_of_the_test_type_draw(monkeypatch):
    """recorded_hours/apnea_events/ahi come from their own stream, separate from
    test_type/channels. If they shared one stream, a change to how one attribute is
    drawn (e.g. widening a channel range) would silently shift every attribute drawn
    after it for any member whose earlier draw happened to land differently -- which
    is exactly what happened when home_type_iv's range widened in the prior fix."""
    members = [f"M{i}" for i in range(30)]
    before = {
        m: generate_sleep_profile(m, seed=3, study_date=STUDY_DATE, target="qualifying")
        for m in members
    }

    # Disjoint from the real (3, 4) range: any member whose drawn type is
    # home_type_iv is guaranteed a different channel count under this patch, so a
    # change here is a meaningful probe, not a no-op.
    monkeypatch.setitem(generate_module._TEST_TYPES, "home_type_iv", (10, 12))

    after = {
        m: generate_sleep_profile(m, seed=3, study_date=STUDY_DATE, target="qualifying")
        for m in members
    }

    assert any(before[m].channels != after[m].channels for m in members), (
        "patch did not move any member's channels -- the probe didn't test anything"
    )
    for m in members:
        assert before[m].recorded_hours == after[m].recorded_hours
        assert before[m].apnea_events == after[m].apnea_events
        assert before[m].ahi == after[m].ahi


def test_an_unknown_target_raises():
    """Silently falling back to a default would produce a golden case that does not test
    what its name says it tests."""
    with pytest.raises(ValueError, match="target"):
        generate_sleep_profile("M1", seed=3, study_date=STUDY_DATE, target="nonsense")


def test_adherent_usage_clears_seventy_percent():
    nights = generate_usage_nights("M1", seed=5, start=date(2026, 2, 1), nights=30)
    qualifying = sum(1 for _, hours in nights if hours >= 4.0)

    assert len(nights) == 30
    assert qualifying / 30 > 0.70


def test_near_miss_adherence_falls_just_short():
    nights = generate_usage_nights(
        "M1", seed=5, start=date(2026, 2, 1), nights=30, target="near_miss_adherence"
    )
    qualifying = sum(1 for _, hours in nights if hours >= 4.0)

    assert 0.60 <= qualifying / 30 < 0.70


def test_usage_nights_are_contiguous_and_unique():
    nights = generate_usage_nights("M1", seed=5, start=date(2026, 2, 1), nights=30)
    days = [night for night, _ in nights]

    assert len(set(days)) == 30
    assert days == sorted(days)


def test_every_target_is_reachable():
    """A target named in TARGETS but unhandled by either generator would fail only
    when a golden case used it -- so call both generators for every name and check
    that exactly one of them accepts it. Asserting a non-empty string proves nothing:
    a target present in TARGETS but missing from a generator's band lookup raises
    KeyError deep inside that generator, not here, and only when someone reaches for it."""
    for target in TARGETS:
        sleep_raised = usage_raised = False

        try:
            generate_sleep_profile("M1", seed=1, study_date=STUDY_DATE, target=target)
        except ValueError:
            sleep_raised = True

        try:
            generate_usage_nights(
                "M1", seed=1, start=date(2026, 2, 1), nights=10, target=target
            )
        except ValueError:
            usage_raised = True

        assert sleep_raised != usage_raised, target
